<a href="https://colab.research.google.com/github/ReutFarkash/useful/blob/main/tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Source: TensorFlow 2.0 Beginner Tutorials<br>
[TensorFlow Tutorial 2 - Tensor Basics](https://www.youtube.com/watch?v=HPjBY1H-U4U&list=PLhhyoLH6IjfxVOdVC1P1L5z5azs0XjMsb&index=2&ab_channel=AladdinPersson)

In [1]:
import tensorflow as tf

In [2]:
# Initialization of Tensor
tf.constant(4, shape=(1,1), dtype=tf.float32)

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[4.]], dtype=float32)>

In [3]:
tf.constant([[1,2,3],[4,5,6]])

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [4]:
tf.ones((3,3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [5]:
tf.zeros((2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [6]:
tf.eye(3)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [7]:
tf.random.normal((3,3), mean=0, stddev=1)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.12036036, -1.7692695 ,  1.2539195 ],
       [-1.2744694 , -0.9383023 ,  0.38669294],
       [-0.5391481 ,  3.0990655 , -0.56143177]], dtype=float32)>

In [8]:
tf.random.uniform((1,3), minval=0, maxval=1)

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0.5325521 , 0.5286511 , 0.16977751]], dtype=float32)>

In [9]:
tf.range(9)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)>

In [10]:
tf.range(start=1, limit=10, delta=2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 3, 5, 7, 9], dtype=int32)>

In [11]:
x = tf.range(start=1, limit=10, delta=2)
tf.cast(x, dtype=tf.float64) # tf.float (16,32,64), tf.int (8,16,32,64), tf.bool

<tf.Tensor: shape=(5,), dtype=float64, numpy=array([1., 3., 5., 7., 9.])>

In [12]:
# Mathamatical Operations
x = tf.constant([1,2,3])
y = tf.constant([9,8,7])

z = tf.add(x,y) # equivalent: z = x + y 
print(z)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [13]:
z = tf.add(x,y) # equivalent: z = x + y 
print(z)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [14]:
z = tf.subtract(x,y) # equivalent: z = x - y 
print(z)

tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)


In [15]:
z = tf.divide(x,y) # equivalent: z = x / y 
print(z)

tf.Tensor([0.11111111 0.25       0.42857143], shape=(3,), dtype=float64)


In [16]:
z = tf.multiply(x,y) # equivalent: z = x * y 
print(z)

tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)


In [17]:
z = tf.tensordot(x, y, axes=1)
print(z)

tf.Tensor(46, shape=(), dtype=int32)


In [18]:
z = tf.reduce_sum(x*y, axis=0)
print(z)

tf.Tensor(46, shape=(), dtype=int32)


In [19]:
z = x ** 5 # elementwise exponantiation
print(z)

tf.Tensor([  1  32 243], shape=(3,), dtype=int32)


In [20]:
x = tf.random.normal((2, 3))
y = tf.random.normal((3, 4))
z = tf.matmul(x, y)
print(z)

tf.Tensor(
[[-3.710259    1.5326009  -1.674188    1.6389418 ]
 [ 1.1900741   0.08207308 -0.52117264  0.51563317]], shape=(2, 4), dtype=float32)


In [21]:
z = x @ y
print(z)

tf.Tensor(
[[-3.710259    1.5326009  -1.674188    1.6389418 ]
 [ 1.1900741   0.08207308 -0.52117264  0.51563317]], shape=(2, 4), dtype=float32)


In [22]:
# Indexing
x = tf.constant([0, 1, 1, 2, 3, 1, 2, 3])
print(x[:])

tf.Tensor([0 1 1 2 3 1 2 3], shape=(8,), dtype=int32)


In [23]:
print(x[1:])

tf.Tensor([1 1 2 3 1 2 3], shape=(7,), dtype=int32)


In [24]:
print(x[1:3])

tf.Tensor([1 1], shape=(2,), dtype=int32)


In [25]:
print(x[::2])

tf.Tensor([0 1 3 2], shape=(4,), dtype=int32)


In [26]:
print(x[::-1])

tf.Tensor([3 2 1 3 2 1 1 0], shape=(8,), dtype=int32)


In [27]:
indices = tf.constant([0, 3])
x_ind = tf.gather(x, indices)
print(x_ind)

tf.Tensor([0 2], shape=(2,), dtype=int32)


In [28]:
x = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])
print(x[0,:])

tf.Tensor([1 2], shape=(2,), dtype=int32)


In [29]:
print(x[0:2,:])

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [30]:
# Reshaping
x = tf.range(9)
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)


In [31]:
x = tf.reshape(x, (3,3))
print(x)

tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)


In [32]:
x = tf.transpose(x, perm=[1,0])
print(x)

tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)


Source: TensorFlow 2.0 Beginner Tutorials<br>
[TensorFlow Tutorial 3 - Neural Networks with Sequential and Functional API](https://www.youtube.com/watch?v=pAhPiF3yiXI&list=PLhhyoLH6IjfxVOdVC1P1L5z5azs0XjMsb&index=3&ab_channel=AladdinPersson)

In [33]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.datasets import mnist

In [34]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()
print(x_train.shape)
print(y_train.shape)

(60000, 28, 28)
(60000,)


In [35]:
x_train = x_train.reshape(-1, 28*28).astype("float32") / 255.0 # flatten so we can load to a NN
x_test = x_test.reshape(-1, 28*28).astype("float32") / 255.0

In [36]:
# Sequential API (very convenient, not very flexable)
model = keras.Sequential(
    [
     layers.Dense(512, activation='relu'),
     layers.Dense(256, activation='relu'),
     layers.Dense(10),
     ]
)

In [37]:
model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.Adam(lr=0.001),
    metrics=["accuracy"]
)

In [38]:
model.fit(x_train, y_train, batch_size=32, epochs=5, verbose=2)
model.evaluate(x_test, y_test, batch_size=32, verbose=2)

Epoch 1/5
1875/1875 - 11s - loss: 0.1856 - accuracy: 0.9431
Epoch 2/5
1875/1875 - 10s - loss: 0.0776 - accuracy: 0.9755
Epoch 3/5
1875/1875 - 10s - loss: 0.0561 - accuracy: 0.9819
Epoch 4/5
1875/1875 - 9s - loss: 0.0420 - accuracy: 0.9864
Epoch 5/5
1875/1875 - 9s - loss: 0.0327 - accuracy: 0.9895
313/313 - 1s - loss: 0.0835 - accuracy: 0.9772


[0.08350013941526413, 0.9771999716758728]

In [39]:
model = keras.Sequential(
    [
     keras.Input(shape=(28*28)), # need this to print model.summary before running model.fit
     layers.Dense(512, activation='relu'),
     layers.Dense(256, activation='relu'),
     layers.Dense(10),
     ]
)

In [40]:
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 512)               401920    
_________________________________________________________________
dense_4 (Dense)              (None, 256)               131328    
_________________________________________________________________
dense_5 (Dense)              (None, 10)                2570      
Total params: 535,818
Trainable params: 535,818
Non-trainable params: 0
_________________________________________________________________
None


In [41]:
model = keras.Sequential() # another way to create the model
model.add(keras.Input(shape=(28*28)))
model.add(layers.Dense(512, activation='relu'))
print(model.summary())
model.add(layers.Dense(256, activation='relu'))
model.add(layers.Dense(10))
print(model.summary())

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_6 (Dense)              (None, 512)               401920    
Total params: 401,920
Trainable params: 401,920
Non-trainable params: 0
_________________________________________________________________
None
Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_6 (Dense)              (None, 512)               401920    
_________________________________________________________________
dense_7 (Dense)              (None, 256)               131328    
_________________________________________________________________
dense_8 (Dense)              (None, 10)                2570      
Total params: 535,818
Trainable params: 535,818
Non-trainable params: 0
_________________________________________________________________
None


In [42]:
# Functional API (a bit more flexable)
inputs = keras.Input(784)
x = layers.Dense(512, activation='relu')(inputs)
x = layers.Dense(256, activation='relu')(x)
outputs = layers.Dense(10, activation='softmax')(x)
model = keras.Model(inputs=inputs, outputs=outputs)

In [43]:
print(model.summary())

Model: "functional_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_3 (InputLayer)         [(None, 784)]             0         
_________________________________________________________________
dense_9 (Dense)              (None, 512)               401920    
_________________________________________________________________
dense_10 (Dense)             (None, 256)               131328    
_________________________________________________________________
dense_11 (Dense)             (None, 10)                2570      
Total params: 535,818
Trainable params: 535,818
Non-trainable params: 0
_________________________________________________________________
None


In [44]:
model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=False),
    optimizer=keras.optimizers.Adam(lr=0.001),
    metrics=["accuracy"]
)

In [45]:
model.fit(x_train, y_train, batch_size=32, epochs=5, verbose=2)
model.evaluate(x_test, y_test, batch_size=32, verbose=2)

Epoch 1/5
1875/1875 - 9s - loss: 0.1855 - accuracy: 0.9439
Epoch 2/5
1875/1875 - 9s - loss: 0.0785 - accuracy: 0.9757
Epoch 3/5
1875/1875 - 9s - loss: 0.0549 - accuracy: 0.9823
Epoch 4/5
1875/1875 - 9s - loss: 0.0422 - accuracy: 0.9863
Epoch 5/5
1875/1875 - 9s - loss: 0.0302 - accuracy: 0.9902
313/313 - 1s - loss: 0.0785 - accuracy: 0.9793


[0.0785420686006546, 0.9793000221252441]

In [46]:
# Functional API (a bit more flexable)
inputs = keras.Input(784)
x = layers.Dense(512, activation='relu', name='first_layer')(inputs)
x = layers.Dense(256, activation='relu', name='second_layer')(x)
outputs = layers.Dense(10, activation='softmax')(x)
model = keras.Model(inputs=inputs, outputs=outputs)

In [47]:
print(model.summary())

Model: "functional_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_4 (InputLayer)         [(None, 784)]             0         
_________________________________________________________________
first_layer (Dense)          (None, 512)               401920    
_________________________________________________________________
second_layer (Dense)         (None, 256)               131328    
_________________________________________________________________
dense_12 (Dense)             (None, 10)                2570      
Total params: 535,818
Trainable params: 535,818
Non-trainable params: 0
_________________________________________________________________
None


In [48]:
model = keras.Sequential()
model.add(keras.Input(shape=(28*28)))
model.add(layers.Dense(512, activation='relu'))
model.add(layers.Dense(256, activation='relu', name='my_layer'))
model.add(layers.Dense(10))

In [49]:
model = keras.Model(inputs=model.inputs,
                    outputs=[model.layers[-2].output]) # or: model.get_layer('my_layer').output
feature = model.predict(x_train)
print(feature.shape)

(60000, 256)


In [50]:
model = keras.Model(inputs=model.inputs,
                    outputs=[layer.output for layer in model.layers])
features = model.predict(x_train)
for feature in features:
  print(feature.shape)

(60000, 784)
(60000, 512)
(60000, 256)
