<a href="https://colab.research.google.com/github/ReutFarkash/useful/blob/main/tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Source: TensorFlow 2.0 Beginner Tutorials<br>
[TensorFlow Tutorial 2 - Tensor Basics](https://www.youtube.com/watch?v=HPjBY1H-U4U&list=PLhhyoLH6IjfxVOdVC1P1L5z5azs0XjMsb&index=2&ab_channel=AladdinPersson)

In [1]:
import tensorflow as tf

In [2]:
# Initialization of Tensor
tf.constant(4, shape=(1,1), dtype=tf.float32)

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[4.]], dtype=float32)>

In [3]:
tf.constant([[1,2,3],[4,5,6]])

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [4]:
tf.ones((3,3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [5]:
tf.zeros((2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [6]:
tf.eye(3)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [7]:
tf.random.normal((3,3), mean=0, stddev=1)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.24589203,  1.2058581 , -0.41952655],
       [ 0.2919698 ,  0.09530945, -0.21929854],
       [-0.9684471 , -1.3014997 , -0.10570682]], dtype=float32)>

In [8]:
tf.random.uniform((1,3), minval=0, maxval=1)

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0.37142527, 0.733068  , 0.21306562]], dtype=float32)>

In [9]:
tf.range(9)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)>

In [10]:
tf.range(start=1, limit=10, delta=2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 3, 5, 7, 9], dtype=int32)>

In [11]:
x = tf.range(start=1, limit=10, delta=2)
tf.cast(x, dtype=tf.float64) # tf.float (16,32,64), tf.int (8,16,32,64), tf.bool

<tf.Tensor: shape=(5,), dtype=float64, numpy=array([1., 3., 5., 7., 9.])>

In [12]:
# Mathamatical Operations
x = tf.constant([1,2,3])
y = tf.constant([9,8,7])

z = tf.add(x,y) # equivalent: z = x + y 
print(z)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [13]:
z = tf.add(x,y) # equivalent: z = x + y 
print(z)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [14]:
z = tf.subtract(x,y) # equivalent: z = x - y 
print(z)

tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)


In [15]:
z = tf.divide(x,y) # equivalent: z = x / y 
print(z)

tf.Tensor([0.11111111 0.25       0.42857143], shape=(3,), dtype=float64)


In [16]:
z = tf.multiply(x,y) # equivalent: z = x * y 
print(z)

tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)


In [17]:
z = tf.tensordot(x, y, axes=1)
print(z)

tf.Tensor(46, shape=(), dtype=int32)


In [18]:
z = tf.reduce_sum(x*y, axis=0)
print(z)

tf.Tensor(46, shape=(), dtype=int32)


In [19]:
z = x ** 5 # elementwise exponantiation
print(z)

tf.Tensor([  1  32 243], shape=(3,), dtype=int32)


In [20]:
x = tf.random.normal((2, 3))
y = tf.random.normal((3, 4))
z = tf.matmul(x, y)
print(z)

tf.Tensor(
[[ 2.9546533  -1.6510837   3.0586374   0.94012403]
 [-3.5683317   2.9453773  -3.2606745   0.57489705]], shape=(2, 4), dtype=float32)


In [21]:
z = x @ y
print(z)

tf.Tensor(
[[ 2.9546533  -1.6510837   3.0586374   0.94012403]
 [-3.5683317   2.9453773  -3.2606745   0.57489705]], shape=(2, 4), dtype=float32)


In [22]:
# Indexing
x = tf.constant([0, 1, 1, 2, 3, 1, 2, 3])
print(x[:])

tf.Tensor([0 1 1 2 3 1 2 3], shape=(8,), dtype=int32)


In [23]:
print(x[1:])

tf.Tensor([1 1 2 3 1 2 3], shape=(7,), dtype=int32)


In [24]:
print(x[1:3])

tf.Tensor([1 1], shape=(2,), dtype=int32)


In [25]:
print(x[::2])

tf.Tensor([0 1 3 2], shape=(4,), dtype=int32)


In [26]:
print(x[::-1])

tf.Tensor([3 2 1 3 2 1 1 0], shape=(8,), dtype=int32)


In [27]:
indices = tf.constant([0, 3])
x_ind = tf.gather(x, indices)
print(x_ind)

tf.Tensor([0 2], shape=(2,), dtype=int32)


In [28]:
x = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])
print(x[0,:])

tf.Tensor([1 2], shape=(2,), dtype=int32)


In [29]:
print(x[0:2,:])

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [30]:
# Reshaping
x = tf.range(9)
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)


In [31]:
x = tf.reshape(x, (3,3))
print(x)

tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)


In [32]:
x = tf.transpose(x, perm=[1,0])
print(x)

tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)


Source: TensorFlow 2.0 Beginner Tutorials<br>
[TensorFlow Tutorial 3 - Neural Networks with Sequential and Functional API](https://www.youtube.com/watch?v=pAhPiF3yiXI&list=PLhhyoLH6IjfxVOdVC1P1L5z5azs0XjMsb&index=3&ab_channel=AladdinPersson)

In [33]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.datasets import mnist

In [34]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()
print(x_train.shape)
print(y_train.shape)

11493376/11490434 [==============================] - 0s 0us/step
(60000, 28, 28)
(60000,)


In [35]:
x_train = x_train.reshape(-1, 28*28).astype("float32") / 255.0 # flatten so we can load to a NN
x_test = x_test.reshape(-1, 28*28).astype("float32") / 255.0

In [36]:
# Sequential API (very convenient, not very flexable)
model = keras.Sequential(
    [
     layers.Dense(512, activation='relu'),
     layers.Dense(256, activation='relu'),
     layers.Dense(10),
     ]
)

In [37]:
model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.Adam(lr=0.001),
    metrics=["accuracy"]
)

In [38]:
model.fit(x_train, y_train, batch_size=32, epochs=5, verbose=2)
model.evaluate(x_test, y_test, batch_size=32, verbose=2)

Epoch 1/5
1875/1875 - 3s - loss: 0.1890 - accuracy: 0.9416
Epoch 2/5
1875/1875 - 3s - loss: 0.0801 - accuracy: 0.9755
Epoch 3/5
1875/1875 - 3s - loss: 0.0550 - accuracy: 0.9829
Epoch 4/5
1875/1875 - 3s - loss: 0.0437 - accuracy: 0.9862
Epoch 5/5
1875/1875 - 3s - loss: 0.0320 - accuracy: 0.9892
313/313 - 0s - loss: 0.0719 - accuracy: 0.9809


[0.07186111807823181, 0.98089998960495]

In [39]:
model = keras.Sequential(
    [
     keras.Input(shape=(28*28)), # need this to print model.summary before running model.fit
     layers.Dense(512, activation='relu'),
     layers.Dense(256, activation='relu'),
     layers.Dense(10),
     ]
)

In [40]:
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 512)               401920    
_________________________________________________________________
dense_4 (Dense)              (None, 256)               131328    
_________________________________________________________________
dense_5 (Dense)              (None, 10)                2570      
Total params: 535,818
Trainable params: 535,818
Non-trainable params: 0
_________________________________________________________________
None


In [41]:
model = keras.Sequential() # another way to create the model
model.add(keras.Input(shape=(28*28)))
model.add(layers.Dense(512, activation='relu'))
print(model.summary())
model.add(layers.Dense(256, activation='relu'))
model.add(layers.Dense(10))
print(model.summary())

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_6 (Dense)              (None, 512)               401920    
Total params: 401,920
Trainable params: 401,920
Non-trainable params: 0
_________________________________________________________________
None
Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_6 (Dense)              (None, 512)               401920    
_________________________________________________________________
dense_7 (Dense)              (None, 256)               131328    
_________________________________________________________________
dense_8 (Dense)              (None, 10)                2570      
Total params: 535,818
Trainable params: 535,818
Non-trainable params: 0
_________________________________________________________________
None


In [42]:
# Functional API (a bit more flexable)
inputs = keras.Input(784)
x = layers.Dense(512, activation='relu')(inputs)
x = layers.Dense(256, activation='relu')(x)
outputs = layers.Dense(10, activation='softmax')(x)
model = keras.Model(inputs=inputs, outputs=outputs)

In [43]:
print(model.summary())

Model: "functional_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_3 (InputLayer)         [(None, 784)]             0         
_________________________________________________________________
dense_9 (Dense)              (None, 512)               401920    
_________________________________________________________________
dense_10 (Dense)             (None, 256)               131328    
_________________________________________________________________
dense_11 (Dense)             (None, 10)                2570      
Total params: 535,818
Trainable params: 535,818
Non-trainable params: 0
_________________________________________________________________
None


In [44]:
model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=False),
    optimizer=keras.optimizers.Adam(lr=0.001),
    metrics=["accuracy"]
)

In [45]:
model.fit(x_train, y_train, batch_size=32, epochs=5, verbose=2)
model.evaluate(x_test, y_test, batch_size=32, verbose=2)

Epoch 1/5
1875/1875 - 3s - loss: 0.1861 - accuracy: 0.9437
Epoch 2/5
1875/1875 - 3s - loss: 0.0800 - accuracy: 0.9758
Epoch 3/5
1875/1875 - 3s - loss: 0.0549 - accuracy: 0.9825
Epoch 4/5
1875/1875 - 3s - loss: 0.0421 - accuracy: 0.9864
Epoch 5/5
1875/1875 - 3s - loss: 0.0336 - accuracy: 0.9890
313/313 - 0s - loss: 0.0808 - accuracy: 0.9808


[0.08075303584337234, 0.9807999730110168]

In [46]:
# Functional API (a bit more flexable)
inputs = keras.Input(784)
x = layers.Dense(512, activation='relu', name='first_layer')(inputs)
x = layers.Dense(256, activation='relu', name='second_layer')(x)
outputs = layers.Dense(10, activation='softmax')(x)
model = keras.Model(inputs=inputs, outputs=outputs)

In [47]:
print(model.summary())

Model: "functional_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_4 (InputLayer)         [(None, 784)]             0         
_________________________________________________________________
first_layer (Dense)          (None, 512)               401920    
_________________________________________________________________
second_layer (Dense)         (None, 256)               131328    
_________________________________________________________________
dense_12 (Dense)             (None, 10)                2570      
Total params: 535,818
Trainable params: 535,818
Non-trainable params: 0
_________________________________________________________________
None


In [48]:
model = keras.Sequential()
model.add(keras.Input(shape=(28*28)))
model.add(layers.Dense(512, activation='relu'))
model.add(layers.Dense(256, activation='relu', name='my_layer'))
model.add(layers.Dense(10))

In [49]:
model = keras.Model(inputs=model.inputs,
                    outputs=[model.layers[-2].output]) # or: model.get_layer('my_layer').output
feature = model.predict(x_train)
print(feature.shape)

(60000, 256)


In [50]:
model = keras.Model(inputs=model.inputs,
                    outputs=[layer.output for layer in model.layers])
features = model.predict(x_train)
for feature in features:
  print(feature.shape)

(60000, 784)
(60000, 512)
(60000, 256)


Source: TensorFlow 2.0 Beginner Tutorials<br>
[TensorFlow Tutorial 4 - Convolutional Neural Networks with Sequential and Functional API](https://www.youtube.com/watch?v=WAciKiDP2bo&ab_channel=AladdinPersson)

In [51]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.datasets import cifar10

In [52]:
(x_train, y_train), (x_test, y_test) = cifar10.load_data()
x_train = x_train.astype("float32") / 255.0
x_test = x_test.astype("float32") / 255.0

170500096/170498071 [==============================] - 4s 0us/step


In [53]:
model = keras.Sequential(
    [
     keras.Input(shape=(32, 32, 3)),
     layers.Conv2D(32, 3, padding='valid', activation='relu'),
     layers.MaxPooling2D(pool_size=(2,2)),
     layers.Conv2D(64, 3, activation='relu'),
     layers.MaxPooling2D(),
     layers.Conv2D(128, 3, activation='relu'),
     layers.Flatten(),
     layers.Dense(64, activation='relu'),
     layers.Dense(10)
    ]
)

In [54]:
print(model.summary())

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 30, 30, 32)        896       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 15, 15, 32)        0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 13, 13, 64)        18496     
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 6, 6, 64)          0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 4, 4, 128)         73856     
_________________________________________________________________
flatten (Flatten)            (None, 2048)              0         
_________________________________________________________________
dense_15 (Dense)             (None, 64)               

In [55]:
model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.Adam(lr=3e-4),
    metrics=["accuracy"],
)

In [56]:
model.fit(x_train, y_train, batch_size=64, epochs=10, verbose=2)
model.evaluate(x_test, y_test, batch_size=64, verbose=2)

Epoch 1/10
782/782 - 2s - loss: 1.6774 - accuracy: 0.3883
Epoch 2/10
782/782 - 2s - loss: 1.3648 - accuracy: 0.5085
Epoch 3/10
782/782 - 2s - loss: 1.2367 - accuracy: 0.5617
Epoch 4/10
782/782 - 2s - loss: 1.1390 - accuracy: 0.5982
Epoch 5/10
782/782 - 2s - loss: 1.0620 - accuracy: 0.6285
Epoch 6/10
782/782 - 2s - loss: 1.0006 - accuracy: 0.6510
Epoch 7/10
782/782 - 2s - loss: 0.9471 - accuracy: 0.6712
Epoch 8/10
782/782 - 2s - loss: 0.9072 - accuracy: 0.6841
Epoch 9/10
782/782 - 2s - loss: 0.8658 - accuracy: 0.7013
Epoch 10/10
782/782 - 2s - loss: 0.8280 - accuracy: 0.7141
157/157 - 0s - loss: 0.8932 - accuracy: 0.6912


[0.8931540250778198, 0.6912000179290771]

In [57]:
def my_model():
  inputs = keras.Input(shape=(32, 32, 3))
  x = layers.Conv2D(32, 3)(inputs)
  x = layers.BatchNormalization()(x)
  x = keras.activations.relu(x)
  x = layers.MaxPooling2D()(x)
  x = layers.Conv2D(64, 5, padding='same')(x)
  x = layers.BatchNormalization()(x)
  x = keras.activations.relu(x)
  x = layers.Conv2D(128, 3)(x)
  x = layers.BatchNormalization()(x)
  x = keras.activations.relu(x)
  x = layers.Flatten()(x)
  x = layers.Dense(64, activation='relu')(x)
  outputs = layers.Dense(10)(x)
  model = keras.Model(inputs=inputs, outputs=outputs)
  return model

In [58]:
model = my_model()
model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.Adam(lr=3e-4),
    metrics=["accuracy"],
)
model.fit(x_train, y_train, batch_size=64, epochs=10, verbose=2)
model.evaluate(x_test, y_test, batch_size=64, verbose=2)

Epoch 1/10
782/782 - 4s - loss: 1.3243 - accuracy: 0.5292
Epoch 2/10
782/782 - 4s - loss: 0.9136 - accuracy: 0.6800
Epoch 3/10
782/782 - 4s - loss: 0.7421 - accuracy: 0.7394
Epoch 4/10
782/782 - 4s - loss: 0.6305 - accuracy: 0.7801
Epoch 5/10
782/782 - 4s - loss: 0.5488 - accuracy: 0.8078
Epoch 6/10
782/782 - 4s - loss: 0.4647 - accuracy: 0.8375
Epoch 7/10
782/782 - 4s - loss: 0.3915 - accuracy: 0.8645
Epoch 8/10
782/782 - 4s - loss: 0.3350 - accuracy: 0.8853
Epoch 9/10
782/782 - 4s - loss: 0.2692 - accuracy: 0.9078
Epoch 10/10
782/782 - 4s - loss: 0.2235 - accuracy: 0.9254
157/157 - 0s - loss: 0.9771 - accuracy: 0.7111


[0.9771324992179871, 0.7110999822616577]

Source: TensorFlow 2.0 Beginner Tutorials<br>
[TensorFlow Tutorial 5 - Adding Regularization with L2 and Dropout](https://www.youtube.com/watch?v=kJSUq1PLmWg&ab_channel=AladdinPersson)

In [59]:
from tensorflow.keras import regularizers

In [64]:
def my_model():
  inputs = keras.Input(shape=(32, 32, 3))
  x = layers.Conv2D(32, 3, padding='same', kernel_regularizer=regularizers.l2(0.01))(inputs)
  x = layers.BatchNormalization()(x)
  x = keras.activations.relu(x)
  x = layers.MaxPooling2D()(x)
  x = layers.Conv2D(64, 5, padding='same', kernel_regularizer=regularizers.l2(0.01))(x)
  x = layers.BatchNormalization()(x)
  x = keras.activations.relu(x)
  x = layers.Conv2D(128, 3, padding='same', kernel_regularizer=regularizers.l2(0.01))(x)
  x = layers.BatchNormalization()(x)
  x = keras.activations.relu(x)
  x = layers.Flatten()(x)
  x = layers.Dense(64, activation='relu', kernel_regularizer=regularizers.l2(0.01))(x)
  outputs = layers.Dense(10)(x)
  model = keras.Model(inputs=inputs, outputs=outputs)
  return model

In [65]:
model = my_model()
model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.Adam(lr=3e-4),
    metrics=["accuracy"],
)
model.fit(x_train, y_train, batch_size=64, epochs=150, verbose=2)
model.evaluate(x_test, y_test, batch_size=64, verbose=2)

Epoch 1/150
782/782 - 4s - loss: 2.6576 - accuracy: 0.4588
Epoch 2/150
782/782 - 4s - loss: 1.4128 - accuracy: 0.6484
Epoch 3/150
782/782 - 4s - loss: 1.1778 - accuracy: 0.6918
Epoch 4/150
782/782 - 4s - loss: 1.0839 - accuracy: 0.7123
Epoch 5/150
782/782 - 4s - loss: 1.0293 - accuracy: 0.7267
Epoch 6/150
782/782 - 4s - loss: 0.9896 - accuracy: 0.7378
Epoch 7/150
782/782 - 4s - loss: 0.9629 - accuracy: 0.7495
Epoch 8/150
782/782 - 4s - loss: 0.9440 - accuracy: 0.7560
Epoch 9/150
782/782 - 4s - loss: 0.9240 - accuracy: 0.7606
Epoch 10/150
782/782 - 4s - loss: 0.9015 - accuracy: 0.7729
Epoch 11/150
782/782 - 4s - loss: 0.9000 - accuracy: 0.7721
Epoch 12/150
782/782 - 4s - loss: 0.8825 - accuracy: 0.7803
Epoch 13/150
782/782 - 4s - loss: 0.8728 - accuracy: 0.7848
Epoch 14/150
782/782 - 4s - loss: 0.8602 - accuracy: 0.7897
Epoch 15/150
782/782 - 4s - loss: 0.8557 - accuracy: 0.7916
Epoch 16/150
782/782 - 4s - loss: 0.8414 - accuracy: 0.7963
Epoch 17/150
782/782 - 4s - loss: 0.8341 - accura

[1.7172490358352661, 0.6851000189781189]

Source: TensorFlow 2.0 Beginner Tutorials<br>
[TensorFlow Tutorial 6 - RNNs, GRUs, LSTMs and Bidirectionality](https://www.youtube.com/watch?v=Ogvd787uJO8&ab_channel=AladdinPersson[link text](https://))

In [66]:
from tensorflow.keras.datasets import mnist

In [67]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train = x_train.astype("float32") / 255.0
x_test = x_test.astype("float32") / 255.0

In [68]:
model = keras.Sequential()
model.add(keras.Input(shape=(None, 28))) # None because we don't have to sepcify the number of time steps
model.add(layers.SimpleRNN(512, return_sequences=True, activation='relu')) # return_sequences=True : return the output from each time step - that way we can stack multiple RNN layers on top of each other
model.add(layers.SimpleRNN(512, activation='relu'))
model.add(layers.Dense(10))
print(model.summary())

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn (SimpleRNN)       (None, None, 512)         276992    
_________________________________________________________________
simple_rnn_1 (SimpleRNN)     (None, 512)               524800    
_________________________________________________________________
dense_21 (Dense)             (None, 10)                5130      
Total params: 806,922
Trainable params: 806,922
Non-trainable params: 0
_________________________________________________________________
None


In [71]:
model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.Adam(lr=0.001),
    metrics=["accuracy"],
)

In [72]:
model.fit(x_train, y_train, batch_size=64, epochs=10, verbose=2)
model.evaluate(x_test, y_test, batch_size=64, verbose=2)

Epoch 1/10
938/938 - 28s - loss: 0.3219 - accuracy: 0.9024
Epoch 2/10
938/938 - 28s - loss: 0.1386 - accuracy: 0.9621
Epoch 3/10
938/938 - 28s - loss: 0.1188 - accuracy: 0.9680
Epoch 4/10
938/938 - 28s - loss: 0.1101 - accuracy: 0.9702
Epoch 5/10
938/938 - 28s - loss: 0.0913 - accuracy: 0.9757
Epoch 6/10
938/938 - 28s - loss: 0.0908 - accuracy: 0.9749
Epoch 7/10
938/938 - 28s - loss: 0.0800 - accuracy: 0.9787
Epoch 8/10
938/938 - 28s - loss: 0.0762 - accuracy: 0.9792
Epoch 9/10
938/938 - 28s - loss: 0.0739 - accuracy: 0.9792
Epoch 10/10
938/938 - 28s - loss: 0.0629 - accuracy: 0.9830
157/157 - 1s - loss: 0.0794 - accuracy: 0.9790


[0.07939868420362473, 0.9789999723434448]

In [73]:
model = keras.Sequential()
model.add(keras.Input(shape=(None, 28))) # None because we don't have to sepcify the number of time steps
model.add(layers.GRU(256, return_sequences=True, activation='tanh')) # return_sequences=True : return the output from each time step - that way we can stack multiple RNN layers on top of each other
model.add(layers.GRU(256, activation='tanh'))
model.add(layers.Dense(10))
print(model.summary())

Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
gru (GRU)                    (None, None, 256)         219648    
_________________________________________________________________
gru_1 (GRU)                  (None, 256)               394752    
_________________________________________________________________
dense_22 (Dense)             (None, 10)                2570      
Total params: 616,970
Trainable params: 616,970
Non-trainable params: 0
_________________________________________________________________
None


In [74]:
model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.Adam(lr=0.001),
    metrics=["accuracy"],
)

model.fit(x_train, y_train, batch_size=64, epochs=10, verbose=2)
model.evaluate(x_test, y_test, batch_size=64, verbose=2)

Epoch 1/10
938/938 - 6s - loss: 0.2762 - accuracy: 0.9079
Epoch 2/10
938/938 - 6s - loss: 0.0686 - accuracy: 0.9789
Epoch 3/10
938/938 - 6s - loss: 0.0465 - accuracy: 0.9854
Epoch 4/10
938/938 - 6s - loss: 0.0350 - accuracy: 0.9893
Epoch 5/10
938/938 - 6s - loss: 0.0305 - accuracy: 0.9902
Epoch 6/10
938/938 - 6s - loss: 0.0250 - accuracy: 0.9920
Epoch 7/10
938/938 - 6s - loss: 0.0205 - accuracy: 0.9937
Epoch 8/10
938/938 - 6s - loss: 0.0195 - accuracy: 0.9938
Epoch 9/10
938/938 - 6s - loss: 0.0170 - accuracy: 0.9945
Epoch 10/10
938/938 - 6s - loss: 0.0164 - accuracy: 0.9943
157/157 - 0s - loss: 0.0397 - accuracy: 0.9883


[0.039734989404678345, 0.9883000254631042]

In [75]:
model = keras.Sequential()
model.add(keras.Input(shape=(None, 28))) # None because we don't have to sepcify the number of time steps
model.add(layers.LSTM(256, return_sequences=True, activation='tanh')) # return_sequences=True : return the output from each time step - that way we can stack multiple RNN layers on top of each other
model.add(layers.LSTM(256, activation='tanh'))
model.add(layers.Dense(10))
print(model.summary())

Model: "sequential_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm (LSTM)                  (None, None, 256)         291840    
_________________________________________________________________
lstm_1 (LSTM)                (None, 256)               525312    
_________________________________________________________________
dense_23 (Dense)             (None, 10)                2570      
Total params: 819,722
Trainable params: 819,722
Non-trainable params: 0
_________________________________________________________________
None


In [76]:
model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.Adam(lr=0.001),
    metrics=["accuracy"],
)

model.fit(x_train, y_train, batch_size=64, epochs=10, verbose=2)
model.evaluate(x_test, y_test, batch_size=64, verbose=2)

Epoch 1/10
938/938 - 7s - loss: 0.2994 - accuracy: 0.9012
Epoch 2/10
938/938 - 7s - loss: 0.0859 - accuracy: 0.9733
Epoch 3/10
938/938 - 7s - loss: 0.0582 - accuracy: 0.9824
Epoch 4/10
938/938 - 7s - loss: 0.0436 - accuracy: 0.9864
Epoch 5/10
938/938 - 7s - loss: 0.0382 - accuracy: 0.9880
Epoch 6/10
938/938 - 7s - loss: 0.0295 - accuracy: 0.9909
Epoch 7/10
938/938 - 7s - loss: 0.0271 - accuracy: 0.9914
Epoch 8/10
938/938 - 7s - loss: 0.0230 - accuracy: 0.9930
Epoch 9/10
938/938 - 7s - loss: 0.0207 - accuracy: 0.9937
Epoch 10/10
938/938 - 7s - loss: 0.0186 - accuracy: 0.9941
157/157 - 1s - loss: 0.0407 - accuracy: 0.9888


[0.04070291295647621, 0.9887999892234802]

In [78]:
model = keras.Sequential()
model.add(keras.Input(shape=(None, 28))) 
model.add(
    layers.Bidirectional(
      layers.LSTM(256, return_sequences=True, activation='tanh')
    ) 
)
model.add(
    layers.Bidirectional(
      layers.LSTM(256, activation='tanh')
    ) 
)
model.add(layers.Dense(10))
print(model.summary())

Model: "sequential_8"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
bidirectional (Bidirectional (None, None, 512)         583680    
_________________________________________________________________
bidirectional_1 (Bidirection (None, 512)               1574912   
_________________________________________________________________
dense_24 (Dense)             (None, 10)                5130      
Total params: 2,163,722
Trainable params: 2,163,722
Non-trainable params: 0
_________________________________________________________________
None


In [79]:
model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.Adam(lr=0.001),
    metrics=["accuracy"],
)

model.fit(x_train, y_train, batch_size=64, epochs=10, verbose=2)
model.evaluate(x_test, y_test, batch_size=64, verbose=2)

Epoch 1/10
938/938 - 14s - loss: 0.2720 - accuracy: 0.9093
Epoch 2/10
938/938 - 14s - loss: 0.0773 - accuracy: 0.9760
Epoch 3/10
938/938 - 14s - loss: 0.0523 - accuracy: 0.9844
Epoch 4/10
938/938 - 14s - loss: 0.0426 - accuracy: 0.9870
Epoch 5/10
938/938 - 14s - loss: 0.0334 - accuracy: 0.9892
Epoch 6/10
938/938 - 14s - loss: 0.0262 - accuracy: 0.9917
Epoch 7/10
938/938 - 14s - loss: 0.0263 - accuracy: 0.9919
Epoch 8/10
938/938 - 14s - loss: 0.0196 - accuracy: 0.9937
Epoch 9/10
938/938 - 14s - loss: 0.0203 - accuracy: 0.9934
Epoch 10/10
938/938 - 14s - loss: 0.0168 - accuracy: 0.9945
157/157 - 1s - loss: 0.0324 - accuracy: 0.9906


[0.03240761533379555, 0.9905999898910522]