<a href="https://colab.research.google.com/github/ReutFarkash/useful/blob/main/tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Source: TensorFlow 2.0 Beginner Tutorials<br>
[TensorFlow Tutorial 2 - Tensor Basics](https://www.youtube.com/watch?v=HPjBY1H-U4U&list=PLhhyoLH6IjfxVOdVC1P1L5z5azs0XjMsb&index=2&ab_channel=AladdinPersson)

In [1]:
import tensorflow as tf

In [2]:
# Initialization of Tensor
tf.constant(4, shape=(1,1), dtype=tf.float32)

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[4.]], dtype=float32)>

In [3]:
tf.constant([[1,2,3],[4,5,6]])

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [4]:
tf.ones((3,3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [5]:
tf.zeros((2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [6]:
tf.eye(3)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [7]:
tf.random.normal((3,3), mean=0, stddev=1)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.2150996 ,  0.8798822 ,  0.35310468],
       [ 0.9684783 , -1.9498274 , -0.70033073],
       [-1.6843494 ,  0.83042365, -1.8962411 ]], dtype=float32)>

In [8]:
tf.random.uniform((1,3), minval=0, maxval=1)

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0.5709326 , 0.22735393, 0.94142234]], dtype=float32)>

In [9]:
tf.range(9)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)>

In [10]:
tf.range(start=1, limit=10, delta=2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 3, 5, 7, 9], dtype=int32)>

In [11]:
x = tf.range(start=1, limit=10, delta=2)
tf.cast(x, dtype=tf.float64) # tf.float (16,32,64), tf.int (8,16,32,64), tf.bool

<tf.Tensor: shape=(5,), dtype=float64, numpy=array([1., 3., 5., 7., 9.])>

In [12]:
# Mathamatical Operations
x = tf.constant([1,2,3])
y = tf.constant([9,8,7])

z = tf.add(x,y) # equivalent: z = x + y 
print(z)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [13]:
z = tf.add(x,y) # equivalent: z = x + y 
print(z)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [14]:
z = tf.subtract(x,y) # equivalent: z = x - y 
print(z)

tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)


In [15]:
z = tf.divide(x,y) # equivalent: z = x / y 
print(z)

tf.Tensor([0.11111111 0.25       0.42857143], shape=(3,), dtype=float64)


In [16]:
z = tf.multiply(x,y) # equivalent: z = x * y 
print(z)

tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)


In [17]:
z = tf.tensordot(x, y, axes=1)
print(z)

tf.Tensor(46, shape=(), dtype=int32)


In [18]:
z = tf.reduce_sum(x*y, axis=0)
print(z)

tf.Tensor(46, shape=(), dtype=int32)


In [19]:
z = x ** 5 # elementwise exponantiation
print(z)

tf.Tensor([  1  32 243], shape=(3,), dtype=int32)


In [20]:
x = tf.random.normal((2, 3))
y = tf.random.normal((3, 4))
z = tf.matmul(x, y)
print(z)

tf.Tensor(
[[-0.199386    0.16229606 -0.45538113 -0.26827267]
 [ 0.1597434   0.15499228 -0.11297336 -0.14542769]], shape=(2, 4), dtype=float32)


In [21]:
z = x @ y
print(z)

tf.Tensor(
[[-0.199386    0.16229606 -0.45538113 -0.26827267]
 [ 0.1597434   0.15499228 -0.11297336 -0.14542769]], shape=(2, 4), dtype=float32)


In [22]:
# Indexing
x = tf.constant([0, 1, 1, 2, 3, 1, 2, 3])
print(x[:])

tf.Tensor([0 1 1 2 3 1 2 3], shape=(8,), dtype=int32)


In [23]:
print(x[1:])

tf.Tensor([1 1 2 3 1 2 3], shape=(7,), dtype=int32)


In [24]:
print(x[1:3])

tf.Tensor([1 1], shape=(2,), dtype=int32)


In [25]:
print(x[::2])

tf.Tensor([0 1 3 2], shape=(4,), dtype=int32)


In [26]:
print(x[::-1])

tf.Tensor([3 2 1 3 2 1 1 0], shape=(8,), dtype=int32)


In [27]:
indices = tf.constant([0, 3])
x_ind = tf.gather(x, indices)
print(x_ind)

tf.Tensor([0 2], shape=(2,), dtype=int32)


In [28]:
x = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])
print(x[0,:])

tf.Tensor([1 2], shape=(2,), dtype=int32)


In [29]:
print(x[0:2,:])

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [30]:
# Reshaping
x = tf.range(9)
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)


In [31]:
x = tf.reshape(x, (3,3))
print(x)

tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)


In [32]:
x = tf.transpose(x, perm=[1,0])
print(x)

tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)
